### ISSUE TITLE
Invite you and your Minecraft Modification to introduce to the player/audience in Taiwan.

### ISSUE THREAD

**Issue by blacklunaer** [Lykrast/DefiledLands#27]
Hello! We are the Cite Media Holding Group. a publisher in Taiwan. For now we’re devoted to Minecraft promotion, Our company is expected to publish a book entitled <The 100 Most Favorite Minecraft Modification for Game Talents> (tentative title) in December. And we will invite well-known Minecraft Game Talents in Taiwan to carefully select the 100 most recommended Minecraft Modification in the world and introduce them to readers with words and pictures. We think that the Modification of Minecraft you created is quite rich in content and suitable for being selected in the 100 recommended lists. To publish this book, we need to obtain your consent to capture the pictures of your game (less than 10, hereinafter referred to as the authorization target) so that vast readers of Minecraft can understand your work through the introduction of this book. Neither party has to pay the fee for this authorization, but in order to protect the rights and interests of both parties, this email will be used as the basis for authorization that you agree to authorize our company to use the authorization target free of charge in <The 100 Most Favorite Minecraft Modification for Game Talents> (tentative name) by means of, but not limited to, reproducing, distributing and public transferring. If you agree to the authorization, please reply to this email directly and fill in the following information (the following information is only for future reference of the authorizers and sending books, which will not be used for other purposes) to just inform us that you "agree to authorize the pictures free of charge". If you would like to provide your address, we would be very happy to present you a book in return after it is published.

Cite Media Holding Group
Vice General Manager
Daniel Wang

Add：10F, No.141, Sec 2, Misheng E. Rd., Thongshan Distric, Taipei City 10483, Taiwan （R.O.C.）
E-MAIL：
blacklunaer@gmail.com

TEL：(02)2500-7600  ext.2670   MOB：0916-252-365

**Comment by Lykrast** [comment]
A github issue is not really an appropriate place for that, but here's my answer so that it's easy to see:

You are free to take and use pictures free of charge under the following conditions:

* This mod is properly credited as `Defiled Lands`
* The author of the mod is properly credited as `Lykrast`
* The source of the mod is provided either as `https://www.curseforge.com/minecraft/mc-mods/defiled-lands` or `https://github.com/Lykrast/DefiledLands`
* ***ADDED BECAUSE I FORGOT*** Do not redistribute the binaries of the mod (the `.jar` file used to put the mod into the game), only link to the official download links (`https://www.curseforge.com/minecraft/mc-mods/defiled-lands`) or through a modpack on CurseForge that includes the mod

For privacy reasons I will not provide my adress here.

But feel free to let me know once the book is ready I'm curious to see how it's gonna look once finished.

**Comment by Lykrast** [comment]
One more condition that I forgot:

* Do not redistribute the binaries of the mod (the `.jar` file used to put the mod into the game), only link to the official download links (`https://www.curseforge.com/minecraft/mc-mods/defiled-lands`) or through a modpack on CurseForge that includes the mod
