### ISSUE TITLE
edit biome id's

### ISSUE THREAD

**Issue by PercyJames** [Lykrast/DefiledLands#29]
**Minecraft version :**
1.12.2
**Defiled Lands version :**
1.12.2-1.4.2

please let us edit biome id's in 1.12.2. please.

**Comment by Lykrast** [comment]
I don't know what issue you're having and not explaining, but I can assure you it's not with the biome ids in this mod.

The biomes are ids are like `defiledlands:plains_defiled` or `defiledlands:forest_tenebra`, which I don't see why you would need to change them or how could they even conflict.

There is no "biome id" number anymore that I'm defining anywhere or that can be changed. If there is any that is used internally it's Forge that's setting them up. If you're getting a conflict there then another mod is the issue.

So unless you actually have a problem or a mod conflict that you can explain and show how to reproduce, then I can't help you further.

**Comment by PercyJames** [comment]
ok, i admit i didn't explain the issue and i'm sorry. all needed info is here https://justpaste.it/81vck

i hope this will provide context. if it doesn't ask me for any needed context

**Comment by Lykrast** [comment]
It's a lot more likely that the issue is caused by JEID, but I don't know enough about Zollern galaxy (I've never heard of it) or Advanced Rocketry planets to help you.

The only thing I can recommend is making a fresh minecraft instance and putting just Zollern, Rocketry and Defiled Lands to see if those work without any other mod you have there.

I'll try to take a look when I have the time, but since it's multiple mods interacting and no one else had that issue so far I can't really do much.

**Comment by PercyJames** [comment]
thank you!
